const countries = [
  {
    value: 1,
    label: "Afghanistan",
    countryCode: "AF",
    currency: "؋",
  },
  {
    value: 2,
    label: "Aland Islands",
    countryCode: "AX",
    currency: "€",
  },
  {
    value: 3,
    label: "Albania",
    countryCode: "AL",
    currency: "Lek",
  },
  {
    value: 4,
    label: "Algeria",
    countryCode: "DZ",
    currency: "دج",
  },
  {
    value: 5,
    label: "American Samoa",
    countryCode: "AS",
    currency: "$",
  },
  {
    value: 6,
    label: "Andorra",
    countryCode: "AD",
    currency: "€",
  },
  {
    value: 7,
    label: "Angola",
    countryCode: "AO",
    currency: "Kz",
  },
  {
    value: 8,
    label: "Anguilla",
    countryCode: "AI",
    currency: "$",
  },
  {
    value: 9,
    label: "Antarctica",
    countryCode: "AQ",
    currency: "$",
  },
  {
    value: 21,
    label: "Belarus",
    countryCode: "BY",
    currency: "Br",
  },
  {
    value: 10,
    label: "Antigua and Barbuda",
    countryCode: "AG",
    currency: "$",
  },
  {
    value: 11,
    label: "Argentina",
    countryCode: "AR",
    currency: "$",
  },
  {
    value: 12,
    label: "Armenia",
    countryCode: "AM",
    currency: "֏",
  },
  {
    value: 13,
    label: "Aruba",
    countryCode: "AW",
    currency: "ƒ",
  },
  {
    value: 14,
    label: "Australia",
    countryCode: "AU",
    currency: "$",
  },
  {
    value: 15,
    label: "Austria",
    countryCode: "AT",
    currency: "€",
  },
  {
    value: 16,
    label: "Azerbaijan",
    countryCode: "AZ",
    currency: "m",
  },
  {
    value: 17,
    label: "The Bahamas",
    countryCode: "BS",
    currency: "B$",
  },
  {
    value: 18,
    label: "Bahrain",
    countryCode: "BH",
    currency: ".د.ب",
  },
  {
    value: 19,
    label: "Bangladesh",
    countryCode: "BD",
    currency: "৳",
  },
  {
    value: 20,
    label: "Barbados",
    countryCode: "BB",
    currency: "Bds$",
  },
  {
    value: 22,
    label: "Belgium",
    countryCode: "BE",
    currency: "€",
  },
  {
    value: 23,
    label: "Belize",
    countryCode: "BZ",
    currency: "$",
  },
  {
    value: 24,
    label: "Benin",
    countryCode: "BJ",
    currency: "CFA",
  },
  {
    value: 25,
    label: "Bermuda",
    countryCode: "BM",
    currency: "$",
  },
  {
    value: 26,
    label: "Bhutan",
    countryCode: "BT",
    currency: "Nu.",
  },
  {
    value: 27,
    label: "Bolivia",
    countryCode: "BO",
    currency: "Bs.",
  },
  {
    value: 28,
    label: "Bosnia and Herzegovina",
    countryCode: "BA",
    currency: "KM",
  },
  {
    value: 29,
    label: "Botswana",
    countryCode: "BW",
    currency: "P",
  },
  {
    value: 30,
    label: "Bouvet Island",
    countryCode: "BV",
    currency: "ko",
  },
  {
    value: 31,
    label: "Brazil",
    countryCode: "BR",
    currency: "R$",
  },
  {
    value: 42,
    label: "Central African Republic",
    countryCode: "CF",
    currency: "FCFA",
  },
  {
    value: 32,
    label: "British Indian Ocean Territory",
    countryCode: "IO",
    currency: "$",
  },
  {
    value: 33,
    label: "Brunei",
    countryCode: "BN",
    currency: "B$",
  },
  {
    value: 34,
    label: "Bulgaria",
    countryCode: "BG",
    currency: "Лв.",
  },
  {
    value: 35,
    label: "Burkina Faso",
    countryCode: "BF",
    currency: "CFA",
  },
  {
    value: 36,
    label: "Burundi",
    countryCode: "BI",
    currency: "FBu",
  },
  {
    value: 37,
    label: "Cambodia",
    countryCode: "KH",
    currency: "KHR",
  },
  {
    value: 38,
    label: "Cameroon",
    countryCode: "CM",
    currency: "FCFA",
  },
  {
    value: 39,
    label: "Canada",
    countryCode: "CA",
    currency: "$",
  },
  {
    value: 40,
    label: "Cape Verde",
    countryCode: "CV",
    currency: "$",
  },
  {
    value: 41,
    label: "Cayman Islands",
    countryCode: "KY",
    currency: "$",
  },
  {
    value: 43,
    label: "Chad",
    countryCode: "TD",
    currency: "FCFA",
  },
  {
    value: 44,
    label: "Chile",
    countryCode: "CL",
    currency: "$",
  },
  {
    value: 45,
    label: "China",
    countryCode: "CN",
    currency: "¥",
  },
  {
    value: 46,
    label: "Christmas Island",
    countryCode: "CX",
    currency: "$",
  },
  {
    value: 47,
    label: "Cocos (Keeling) Islands",
    countryCode: "CC",
    currency: "$",
  },
  {
    value: 48,
    label: "Colombia",
    countryCode: "CO",
    currency: "$",
  },
  {
    value: 49,
    label: "Comoros",
    countryCode: "KM",
    currency: "CF",
  },
  {
    value: 50,
    label: "Congo",
    countryCode: "CG",
    currency: "FC",
  },
  {
    value: 51,
    label: "Democratic Republic of the Congo",
    countryCode: "CD",
    currency: "FC",
  },
  {
    value: 52,
    label: "Cook Islands",
    countryCode: "CK",
    currency: "$",
  },
  {
    value: 53,
    label: "Costa Rica",
    countryCode: "CR",
    currency: "₡",
  },
  {
    value: 54,
    label: "Cote D'Ivoire (Ivory Coast)",
    countryCode: "CI",
    currency: "CFA",
  },
  {
    value: 55,
    label: "Croatia",
    countryCode: "HR",
    currency: "€",
  },
  {
    value: 56,
    label: "Cuba",
    countryCode: "CU",
    currency: "$",
  },
  {
    value: 57,
    label: "Cyprus",
    countryCode: "CY",
    currency: "€",
  },
  {
    value: 58,
    label: "Czech Republic",
    countryCode: "CZ",
    currency: "Kč",
  },
  {
    value: 59,
    label: "Denmark",
    countryCode: "DK",
    currency: "Kr.",
  },
  {
    value: 60,
    label: "Djibouti",
    countryCode: "DJ",
    currency: "Fdj",
  },
  {
    value: 61,
    label: "Dominica",
    countryCode: "DM",
    currency: "$",
  },
  {
    value: 62,
    label: "Dominican Republic",
    countryCode: "DO",
    currency: "$",
  },
  {
    value: 63,
    label: "Timor-Leste",
    countryCode: "TL",
    currency: "$",
  },
  {
    value: 64,
    label: "Ecuador",
    countryCode: "EC",
    currency: "$",
  },
  {
    value: 65,
    label: "Egypt",
    countryCode: "EG",
    currency: "ج.م",
  },
  {
    value: 66,
    label: "El Salvador",
    countryCode: "SV",
    currency: "$",
  },
  {
    value: 67,
    label: "Equatorial Guinea",
    countryCode: "GQ",
    currency: "FCFA",
  },
  {
    value: 68,
    label: "Eritrea",
    countryCode: "ER",
    currency: "Nfk",
  },
  {
    value: 69,
    label: "Estonia",
    countryCode: "EE",
    currency: "€",
  },
  {
    value: 70,
    label: "Ethiopia",
    countryCode: "ET",
    currency: "Nkf",
  },
  {
    value: 71,
    label: "Falkland Islands",
    countryCode: "FK",
    currency: "£",
  },
  {
    value: 72,
    label: "Faroe Islands",
    countryCode: "FO",
    currency: "Kr.",
  },
  {
    value: 73,
    label: "Fiji Islands",
    countryCode: "FJ",
    currency: "FJ$",
  },
  {
    value: 74,
    label: "Finland",
    countryCode: "FI",
    currency: "€",
  },
  {
    value: 75,
    label: "France",
    countryCode: "FR",
    currency: "€",
  },
  {
    value: 76,
    label: "French Guiana",
    countryCode: "GF",
    currency: "€",
  },
  {
    value: 77,
    label: "French Polynesia",
    countryCode: "PF",
    currency: "₣",
  },
  {
    value: 78,
    label: "French Southern Territories",
    countryCode: "TF",
    currency: "€",
  },
  {
    value: 79,
    label: "Gabon",
    countryCode: "GA",
    currency: "FCFA",
  },
  {
    value: 80,
    label: "The Gambia ",
    countryCode: "GM",
    currency: "D",
  },
  {
    value: 81,
    label: "Georgia",
    countryCode: "GE",
    currency: "ლ",
  },
  {
    value: 82,
    label: "Germany",
    countryCode: "DE",
    currency: "€",
  },
  {
    value: 83,
    label: "Ghana",
    countryCode: "GH",
    currency: "GH₵",
  },
  {
    value: 84,
    label: "Gibraltar",
    countryCode: "GI",
    currency: "£",
  },
  {
    value: 85,
    label: "Greece",
    countryCode: "GR",
    currency: "€",
  },
  {
    value: 86,
    label: "Greenland",
    countryCode: "GL",
    currency: "Kr.",
  },
  {
    value: 87,
    label: "Grenada",
    countryCode: "GD",
    currency: "$",
  },
  {
    value: 88,
    label: "Guadeloupe",
    countryCode: "GP",
    currency: "€",
  },
  {
    value: 89,
    label: "Guam",
    countryCode: "GU",
    currency: "$",
  },
  {
    value: 90,
    label: "Guatemala",
    countryCode: "GT",
    currency: "Q",
  },
  {
    value: 91,
    label: "Guernsey and Alderney",
    countryCode: "GG",
    currency: "£",
  },
  {
    value: 92,
    label: "Guinea",
    countryCode: "GN",
    currency: "FG",
  },
  {
    value: 93,
    label: "Guinea-Bissau",
    countryCode: "GW",
    currency: "CFA",
  },
  {
    value: 94,
    label: "Guyana",
    countryCode: "GY",
    currency: "$",
  },
  {
    value: 95,
    label: "Haiti",
    countryCode: "HT",
    currency: "G",
  },
  {
    value: 96,
    label: "Heard Island and McDonald Islands",
    countryCode: "HM",
    currency: "$",
  },
  {
    value: 97,
    label: "Honduras",
    countryCode: "HN",
    currency: "L",
  },
  {
    value: 98,
    label: "Hong Kong S.A.R.",
    countryCode: "HK",
    currency: "$",
  },
  {
    value: 99,
    label: "Hungary",
    countryCode: "HU",
    currency: "Ft",
  },
  {
    value: 100,
    label: "Iceland",
    countryCode: "IS",
    currency: "ko",
  },
  {
    value: 101,
    label: "India",
    countryCode: "IN",
    currency: "₹",
  },
  {
    value: 102,
    label: "Indonesia",
    countryCode: "ID",
    currency: "Rp",
  },
  {
    value: 103,
    label: "Iran",
    countryCode: "IR",
    currency: "﷼",
  },
  {
    value: 104,
    label: "Iraq",
    countryCode: "IQ",
    currency: "د.ع",
  },
  {
    value: 105,
    label: "Ireland",
    countryCode: "IE",
    currency: "€",
  },
  {
    value: 106,
    label: "Israel",
    countryCode: "IL",
    currency: "₪",
  },
  {
    value: 107,
    label: "Italy",
    countryCode: "IT",
    currency: "€",
  },
  {
    value: 108,
    label: "Jamaica",
    countryCode: "JM",
    currency: "J$",
  },
  {
    value: 109,
    label: "Japan",
    countryCode: "JP",
    currency: "¥",
  },
  {
    value: 110,
    label: "Jersey",
    countryCode: "JE",
    currency: "£",
  },
  {
    value: 111,
    label: "Jordan",
    countryCode: "JO",
    currency: "ا.د",
  },
  {
    value: 112,
    label: "Kazakhstan",
    countryCode: "KZ",
    currency: "лв",
  },
  {
    value: 113,
    label: "Kenya",
    countryCode: "KE",
    currency: "KSh",
  },
  {
    value: 114,
    label: "Kiribati",
    countryCode: "KI",
    currency: "$",
  },
  {
    value: 115,
    label: "North Korea",
    countryCode: "KP",
    currency: "₩",
  },
  {
    value: 116,
    label: "South Korea",
    countryCode: "KR",
    currency: "₩",
  },
  {
    value: 162,
    label: "Niue",
    countryCode: "NU",
    currency: "$",
  },
  {
    value: 117,
    label: "Kuwait",
    countryCode: "KW",
    currency: "ك.د",
  },
  {
    value: 118,
    label: "Kyrgyzstan",
    countryCode: "KG",
    currency: "лв",
  },
  {
    value: 119,
    label: "Laos",
    countryCode: "LA",
    currency: "₭",
  },
  {
    value: 120,
    label: "Latvia",
    countryCode: "LV",
    currency: "€",
  },
  {
    value: 121,
    label: "Lebanon",
    countryCode: "LB",
    currency: "£",
  },
  {
    value: 122,
    label: "Lesotho",
    countryCode: "LS",
    currency: "L",
  },
  {
    value: 123,
    label: "Liberia",
    countryCode: "LR",
    currency: "$",
  },
  {
    value: 124,
    label: "Libya",
    countryCode: "LY",
    currency: "د.ل",
  },
  {
    value: 125,
    label: "Liechtenstein",
    countryCode: "LI",
    currency: "CHf",
  },
  {
    value: 126,
    label: "Lithuania",
    countryCode: "LT",
    currency: "€",
  },
  {
    value: 127,
    label: "Luxembourg",
    countryCode: "LU",
    currency: "€",
  },
  {
    value: 128,
    label: "Macau S.A.R.",
    countryCode: "MO",
    currency: "$",
  },
  {
    value: 129,
    label: "North Macedonia",
    countryCode: "MK",
    currency: "ден",
  },
  {
    value: 130,
    label: "Madagascar",
    countryCode: "MG",
    currency: "Ar",
  },
  {
    value: 131,
    label: "Malawi",
    countryCode: "MW",
    currency: "MK",
  },
  {
    value: 132,
    label: "Malaysia",
    countryCode: "MY",
    currency: "RM",
  },
  {
    value: 133,
    label: "Maldives",
    countryCode: "MV",
    currency: "Rf",
  },
  {
    value: 134,
    label: "Mali",
    countryCode: "ML",
    currency: "CFA",
  },
  {
    value: 135,
    label: "Malta",
    countryCode: "MT",
    currency: "€",
  },
  {
    value: 136,
    label: "Man (Isle of)",
    countryCode: "IM",
    currency: "£",
  },
  {
    value: 137,
    label: "Marshall Islands",
    countryCode: "MH",
    currency: "$",
  },
  {
    value: 138,
    label: "Martinique",
    countryCode: "MQ",
    currency: "€",
  },
  {
    value: 139,
    label: "Mauritania",
    countryCode: "MR",
    currency: "MRU",
  },
  {
    value: 140,
    label: "Mauritius",
    countryCode: "MU",
    currency: "₨",
  },
  {
    value: 141,
    label: "Mayotte",
    countryCode: "YT",
    currency: "€",
  },
  {
    value: 142,
    label: "Mexico",
    countryCode: "MX",
    currency: "$",
  },
  {
    value: 143,
    label: "Micronesia",
    countryCode: "FM",
    currency: "$",
  },
  {
    value: 144,
    label: "Moldova",
    countryCode: "MD",
    currency: "L",
  },
  {
    value: 145,
    label: "Monaco",
    countryCode: "MC",
    currency: "€",
  },
  {
    value: 146,
    label: "Mongolia",
    countryCode: "MN",
    currency: "₮",
  },
  {
    value: 147,
    label: "Montenegro",
    countryCode: "ME",
    currency: "€",
  },
  {
    value: 148,
    label: "Montserrat",
    countryCode: "MS",
    currency: "$",
  },
  {
    value: 149,
    label: "Morocco",
    countryCode: "MA",
    currency: "DH",
  },
  {
    value: 150,
    label: "Mozambique",
    countryCode: "MZ",
    currency: "MT",
  },
  {
    value: 151,
    label: "Myanmar",
    countryCode: "MM",
    currency: "K",
  },
  {
    value: 152,
    label: "Namibia",
    countryCode: "NA",
    currency: "$",
  },
  {
    value: 153,
    label: "Nauru",
    countryCode: "NR",
    currency: "$",
  },
  {
    value: 154,
    label: "Nepal",
    countryCode: "NP",
    currency: "₨",
  },
  {
    value: 155,
    label: "Bonaire, Sint Eustatius and Saba",
    countryCode: "BQ",
    currency: "$",
  },
  {
    value: 156,
    label: "Netherlands",
    countryCode: "NL",
    currency: "€",
  },
  {
    value: 157,
    label: "New Caledonia",
    countryCode: "NC",
    currency: "₣",
  },
  {
    value: 158,
    label: "New Zealand",
    countryCode: "NZ",
    currency: "$",
  },
  {
    value: 159,
    label: "Nicaragua",
    countryCode: "NI",
    currency: "C$",
  },
  {
    value: 160,
    label: "Niger",
    countryCode: "NE",
    currency: "CFA",
  },
  {
    value: 161,
    label: "Nigeria",
    countryCode: "NG",
    currency: "₦",
  },
  {
    value: 163,
    label: "Norfolk Island",
    countryCode: "NF",
    currency: "$",
  },
  {
    value: 164,
    label: "Northern Mariana Islands",
    countryCode: "MP",
    currency: "$",
  },
  {
    value: 165,
    label: "Norway",
    countryCode: "NO",
    currency: "ko",
  },
  {
    value: 166,
    label: "Oman",
    countryCode: "OM",
    currency: ".ع.ر",
  },
  {
    value: 167,
    label: "Pakistan",
    countryCode: "PK",
    currency: "₨",
  },
  {
    value: 168,
    label: "Palau",
    countryCode: "PW",
    currency: "$",
  },
  {
    value: 169,
    label: "Palestinian Territory Occupied",
    countryCode: "PS",
    currency: "₪",
  },
  {
    value: 170,
    label: "Panama",
    countryCode: "PA",
    currency: "B/.",
  },
  {
    value: 171,
    label: "Papua New Guinea",
    countryCode: "PG",
    currency: "K",
  },
  {
    value: 172,
    label: "Paraguay",
    countryCode: "PY",
    currency: "₲",
  },
  {
    value: 173,
    label: "Peru",
    countryCode: "PE",
    currency: "S/.",
  },
  {
    value: 174,
    label: "Philippines",
    countryCode: "PH",
    currency: "₱",
  },
  {
    value: 175,
    label: "Pitcairn Island",
    countryCode: "PN",
    currency: "$",
  },
  {
    value: 176,
    label: "Poland",
    countryCode: "PL",
    currency: "zł",
  },
  {
    value: 177,
    label: "Portugal",
    countryCode: "PT",
    currency: "€",
  },
  {
    value: 178,
    label: "Puerto Rico",
    countryCode: "PR",
    currency: "$",
  },
  {
    value: 179,
    label: "Qatar",
    countryCode: "QA",
    currency: "ق.ر",
  },
  {
    value: 180,
    label: "Reunion",
    countryCode: "RE",
    currency: "€",
  },
  {
    value: 181,
    label: "Romania",
    countryCode: "RO",
    currency: "lei",
  },
  {
    value: 182,
    label: "Russia",
    countryCode: "RU",
    currency: "₽",
  },
  {
    value: 183,
    label: "Rwanda",
    countryCode: "RW",
    currency: "FRw",
  },
  {
    value: 214,
    label: "Switzerland",
    countryCode: "CH",
    currency: "CHf",
  },
  {
    value: 184,
    label: "Saint Helena",
    countryCode: "SH",
    currency: "£",
  },
  {
    value: 185,
    label: "Saint Kitts and Nevis",
    countryCode: "KN",
    currency: "$",
  },
  {
    value: 186,
    label: "Saint Lucia",
    countryCode: "LC",
    currency: "$",
  },
  {
    value: 187,
    label: "Saint Pierre and Miquelon",
    countryCode: "PM",
    currency: "€",
  },
  {
    value: 188,
    label: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    currency: "$",
  },
  {
    value: 189,
    label: "Saint-Barthelemy",
    countryCode: "BL",
    currency: "€",
  },
  {
    value: 190,
    label: "Saint-Martin (French part)",
    countryCode: "MF",
    currency: "€",
  },
  {
    value: 191,
    label: "Samoa",
    countryCode: "WS",
    currency: "SAT",
  },
  {
    value: 192,
    label: "San Marino",
    countryCode: "SM",
    currency: "€",
  },
  {
    value: 193,
    label: "Sao Tome and Principe",
    countryCode: "ST",
    currency: "Db",
  },
  {
    value: 194,
    label: "Saudi Arabia",
    countryCode: "SA",
    currency: "﷼",
  },
  {
    value: 195,
    label: "Senegal",
    countryCode: "SN",
    currency: "CFA",
  },
  {
    value: 196,
    label: "Serbia",
    countryCode: "RS",
    currency: "din",
  },
  {
    value: 197,
    label: "Seychelles",
    countryCode: "SC",
    currency: "SRe",
  },
  {
    value: 198,
    label: "Sierra Leone",
    countryCode: "SL",
    currency: "Le",
  },
  {
    value: 199,
    label: "Singapore",
    countryCode: "SG",
    currency: "$",
  },
  {
    value: 200,
    label: "Slovakia",
    countryCode: "SK",
    currency: "€",
  },
  {
    value: 201,
    label: "Slovenia",
    countryCode: "SI",
    currency: "€",
  },
  {
    value: 202,
    label: "Solomon Islands",
    countryCode: "SB",
    currency: "Si$",
  },
  {
    value: 203,
    label: "Somalia",
    countryCode: "SO",
    currency: "Sh.so.",
  },
  {
    value: 204,
    label: "South Africa",
    countryCode: "ZA",
    currency: "R",
  },
  {
    value: 205,
    label: "South Georgia",
    countryCode: "GS",
    currency: "£",
  },
  {
    value: 206,
    label: "South Sudan",
    countryCode: "SS",
    currency: "£",
  },
  {
    value: 207,
    label: "Spain",
    countryCode: "ES",
    currency: "€",
  },
  {
    value: 208,
    label: "Sri Lanka",
    countryCode: "LK",
    currency: "Rs",
  },
  {
    value: 209,
    label: "Sudan",
    countryCode: "SD",
    currency: ".س.ج",
  },
  {
    value: 210,
    label: "Suriname",
    countryCode: "SR",
    currency: "$",
  },
  {
    value: 211,
    label: "Svalbard and Jan Mayen Islands",
    countryCode: "SJ",
    currency: "ko",
  },
  {
    value: 212,
    label: "Eswatini",
    countryCode: "SZ",
    currency: "E",
  },
  {
    value: 213,
    label: "Sweden",
    countryCode: "SE",
    currency: "ko",
  },
  {
    value: 215,
    label: "Syria",
    countryCode: "SY",
    currency: "LS",
  },
  {
    value: 216,
    label: "Taiwan",
    countryCode: "TW",
    currency: "$",
  },
  {
    value: 217,
    label: "Tajikistan",
    countryCode: "TJ",
    currency: "SM",
  },
  {
    value: 218,
    label: "Tanzania",
    countryCode: "TZ",
    currency: "TSh",
  },
  {
    value: 219,
    label: "Thailand",
    countryCode: "TH",
    currency: "฿",
  },
  {
    value: 220,
    label: "Togo",
    countryCode: "TG",
    currency: "CFA",
  },
  {
    value: 221,
    label: "Tokelau",
    countryCode: "TK",
    currency: "$",
  },
  {
    value: 222,
    label: "Tonga",
    countryCode: "TO",
    currency: "$",
  },
  {
    value: 223,
    label: "Trinidad and Tobago",
    countryCode: "TT",
    currency: "$",
  },
  {
    value: 224,
    label: "Tunisia",
    countryCode: "TN",
    currency: "ت.د",
  },
  {
    value: 225,
    label: "Turkey",
    countryCode: "TR",
    currency: "₺",
  },
  {
    value: 226,
    label: "Turkmenistan",
    countryCode: "TM",
    currency: "T",
  },
  {
    value: 227,
    label: "Turks and Caicos Islands",
    countryCode: "TC",
    currency: "$",
  },
  {
    value: 228,
    label: "Tuvalu",
    countryCode: "TV",
    currency: "$",
  },
  {
    value: 229,
    label: "Uganda",
    countryCode: "UG",
    currency: "USh",
  },
  {
    value: 230,
    label: "Ukraine",
    countryCode: "UA",
    currency: "₴",
  },
  {
    value: 231,
    label: "United Arab Emirates",
    countryCode: "AE",
    currency: "إ.د",
  },
  {
    value: 232,
    label: "United Kingdom",
    countryCode: "GB",
    currency: "£",
  },
  {
    value: 233,
    label: "United States",
    countryCode: "US",
    currency: "$",
  },
  {
    value: 234,
    label: "United States Minor Outlying Islands",
    countryCode: "UM",
    currency: "$",
  },
  {
    value: 235,
    label: "Uruguay",
    countryCode: "UY",
    currency: "$",
  },
  {
    value: 236,
    label: "Uzbekistan",
    countryCode: "UZ",
    currency: "лв",
  },
  {
    value: 237,
    label: "Vanuatu",
    countryCode: "VU",
    currency: "VT",
  },
  {
    value: 238,
    label: "Vatican City State (Holy See)",
    countryCode: "VA",
    currency: "€",
  },
  {
    value: 239,
    label: "Venezuela",
    countryCode: "VE",
    currency: "Bs",
  },
  {
    value: 240,
    label: "Vietnam",
    countryCode: "VN",
    currency: "₫",
  },
  {
    value: 241,
    label: "Virgin Islands (British)",
    countryCode: "VG",
    currency: "$",
  },
  {
    value: 242,
    label: "Virgin Islands (US)",
    countryCode: "VI",
    currency: "$",
  },
  {
    value: 243,
    label: "Wallis and Futuna Islands",
    countryCode: "WF",
    currency: "₣",
  },
  {
    value: 244,
    label: "Western Sahara",
    countryCode: "EH",
    currency: "MAD",
  },
  {
    value: 245,
    label: "Yemen",
    countryCode: "YE",
    currency: "﷼",
  },
  {
    value: 246,
    label: "Zambia",
    countryCode: "ZM",
    currency: "ZK",
  },
  {
    value: 247,
    label: "Zimbabwe",
    countryCode: "ZW",
    currency: "$",
  },
  {
    value: 248,
    label: "Kosovo",
    countryCode: "XK",
    currency: "€",
  },
  {
    value: 249,
    label: "Curaçao",
    countryCode: "CW",
    currency: "ƒ",
  },
  {
    value: 250,
    label: "Sint Maarten (Dutch part)",
    countryCode: "SX",
    currency: "ƒ",
  },
];
export default countries;
