import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import type { PropsWithChildren } from "react";
import { ApolloWrapper } from "../lib/apollo-client";
import { GlobalStateWrapper } from "../lib/auth-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <GlobalStateWrapper>{children}</GlobalStateWrapper>
        </ApolloWrapper>
      </body>
    </html>
  );
}
