export const USERNAME_MAX_LENGTH=30
export const NAME_MAX_LENGTH=30
export const BIO_MAX_LENGTH=200
export const POSTING_BIO_MAX_LENGTH=1500
export const PORTFOLIO_CAPTION_MAX_LENGTH=64
export const MAX_CAMPAIGNS=6